name: html scraper

on:
  schedule:
    - cron: "0 0 */1 * *" # every day
  
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Spider
        run: scrapy runspider -O pdf_files.json scraper.py

      - name: commit file
        run: |
          git config --local user.email "foiscraper@users.noreply.github.com"
          git config --local user.name "foi.scraper"
          git add pdf_files.json
          git commit -m "bot: updated at $(date)"
          git push